/**
 * Blue-noise dither, applied to the final output.
 *
 * The texture is a 128x128 void-and-cluster permutation of 0..255 generated by
 * tools/gen-bluenoise.mjs. It tiles, so the only work per pixel is a wrapped
 * lookup. `u_blueNoiseOffset` moves the tile every frame; a static pattern is
 * visible as a fixed grain once the eye locks onto it, an animated one reads as
 * film. Amplitude is exactly one 8-bit step, which is enough to break a band
 * without being perceptible as noise.
 */
export const BLUE_NOISE = /* glsl */ `
uniform sampler2D u_blueNoise;
uniform vec2 u_blueNoiseScale;
uniform vec2 u_blueNoiseOffset;
uniform float u_ditherAmount;

float getBlueNoise(vec2 coord) {
  return texture2D(u_blueNoise, coord * u_blueNoiseScale + u_blueNoiseOffset).r;
}

/** Triangular-PDF dither: two taps subtracted give +/-1 step with a triangular
 *  distribution, which removes the residual mean shift a uniform dither leaves
 *  behind in flat areas. */
vec3 ditherOutput(vec3 color, vec2 coord) {
  float n0 = getBlueNoise(coord);
  float n1 = getBlueNoise(coord + vec2(0.5));
  return color + vec3((n0 - n1) / 255.0) * u_ditherAmount;
}
`;

export const BLUE_NOISE_TEXTURE_SIZE = 128;
